DROP TABLE IF EXISTS SuperHeroes;

CREATE TABLE SuperHeroes ( 
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(1000) NOT NULL,
    FirstName VARCHAR(1000) NOT NULL,
    LastName VARCHAR(1000) NULL,
    Place VARCHAR(1000) NULL,
);